language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-leanr' ]; then cd .. && eval "mv $currentfolder generator-leanr" && cd generator-leanr; fi

